sudo: required
language: php

php:
  - 7.1
  - 7.2

services:
  - mysql

jdk:
  - oraclejdk8

before_script:
  - cp .env.travis .env
  - mysql -e 'create database monica;'
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - vendor/bin/phpunit --log-junit junit.xml --coverage-clover clover.xml
  - test "$TRAVIS_PHP_VERSION" == "7.1" && ./travis-sonar.sh

cache:
  directories:
    - $HOME/.sonar/cache
    - $HOME/sonarscanner
    - $HOME/sonarlauncher
